const { RESOURCE_NAMES } = require("../../models/resources");

const API_V1_ROUTES = [
  {
    method: "OPTIONS",
    path: "/api/v1/auth/registration",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "RegisterUserRequest",
    responseSchema: "AuthSessionResponse",
    authRequired: false,
  },
  {
    method: "POST",
    path: "/api/v1/auth/registration",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "RegisterUserRequest",
    responseSchema: "AuthSessionResponse",
    authRequired: false,
  },
  {
    method: "POST",
    path: "/api/v1/auth/sync-user",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "RegisterUserRequest",
    responseSchema: "AuthUserResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/auth/me",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "Empty",
    responseSchema: "AuthUserResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/auth/me",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "RegisterUserRequest",
    responseSchema: "AuthUserResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/auth/me",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/auth/consents",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "ConsentRequest",
    responseSchema: "ConsentResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/auth/consents/{consentType}",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "ConsentRequest",
    responseSchema: "ConsentResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/auth/consents/{consentType}",
    resource: RESOURCE_NAMES.auth,
    requestSchema: "ConsentRequest",
    responseSchema: "ConsentResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/assessments/templates",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "Empty",
    responseSchema: "AssessmentTemplateListResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/assessments/templates/{slug}",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "Empty",
    responseSchema: "AssessmentTemplateResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/assessments/submissions",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "AssessmentSubmissionRequest",
    responseSchema: "AssessmentSubmissionResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/assessments/submissions/{submissionId}",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "AssessmentSubmissionRequest",
    responseSchema: "AssessmentSubmissionResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/assessments/submissions/{submissionId}",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "AssessmentSubmissionRequest",
    responseSchema: "AssessmentSubmissionResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/assessments/submissions/{submissionId}",
    resource: RESOURCE_NAMES.assessments,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/journal/entries",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "JournalEntryQuery",
    responseSchema: "JournalEntryListResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/journal/entries",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "JournalEntryUpsert",
    responseSchema: "JournalEntryResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/journal/entries/{entryId}",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "Empty",
    responseSchema: "JournalEntryResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/journal/entries/{entryId}",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "JournalEntryUpsert",
    responseSchema: "JournalEntryResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/journal/entries/{entryId}",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "JournalEntryUpsert",
    responseSchema: "JournalEntryResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/journal/entries/{entryId}",
    resource: RESOURCE_NAMES.journal,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/fasting/sessions",
    resource: RESOURCE_NAMES.fasting,
    requestSchema: "Empty",
    responseSchema: "FastingSessionListResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/fasting/sessions",
    resource: RESOURCE_NAMES.fasting,
    requestSchema: "FastingSessionRequest",
    responseSchema: "FastingSessionResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/fasting/sessions/{sessionId}",
    resource: RESOURCE_NAMES.fasting,
    requestSchema: "FastingSessionRequest",
    responseSchema: "FastingSessionResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/fasting/sessions/{sessionId}",
    resource: RESOURCE_NAMES.fasting,
    requestSchema: "FastingSessionRequest",
    responseSchema: "FastingSessionResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/fasting/sessions/{sessionId}",
    resource: RESOURCE_NAMES.fasting,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/autocura/programs",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "Empty",
    responseSchema: "AutocuraProgramListResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/autocura/programs/{programSlug}/contents",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "Empty",
    responseSchema: "AutocuraContentListResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/autocura/sessions",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "Empty",
    responseSchema: "AutocuraSessionListResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/autocura/sessions",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "AutocuraSessionRequest",
    responseSchema: "AutocuraSessionResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/autocura/sessions/{sessionId}",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "AutocuraSessionRequest",
    responseSchema: "AutocuraSessionResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/autocura/sessions/{sessionId}",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "AutocuraSessionRequest",
    responseSchema: "AutocuraSessionResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/autocura/sessions/{sessionId}",
    resource: RESOURCE_NAMES.autocura,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/progress/modules",
    resource: RESOURCE_NAMES.progress,
    requestSchema: "Empty",
    responseSchema: "UserProgressListResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/progress/modules/{moduleSlug}",
    resource: RESOURCE_NAMES.progress,
    requestSchema: "UserProgressRequest",
    responseSchema: "UserProgressResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/progress/modules/{moduleSlug}",
    resource: RESOURCE_NAMES.progress,
    requestSchema: "UserProgressRequest",
    responseSchema: "UserProgressResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/progress/modules/{moduleSlug}",
    resource: RESOURCE_NAMES.progress,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
  {
    method: "GET",
    path: "/api/v1/evolucao/series",
    resource: RESOURCE_NAMES.evolucao,
    requestSchema: "EvolutionSeriesQuery",
    responseSchema: "EvolutionSeriesResponse",
    authRequired: true,
  },
  {
    method: "POST",
    path: "/api/v1/evolucao/snapshots",
    resource: RESOURCE_NAMES.evolucao,
    requestSchema: "EvolutionSnapshotRequest",
    responseSchema: "EvolutionSnapshotResponse",
    authRequired: true,
  },
  {
    method: "PUT",
    path: "/api/v1/evolucao/snapshots/{snapshotId}",
    resource: RESOURCE_NAMES.evolucao,
    requestSchema: "EvolutionSnapshotRequest",
    responseSchema: "EvolutionSnapshotResponse",
    authRequired: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/evolucao/snapshots/{snapshotId}",
    resource: RESOURCE_NAMES.evolucao,
    requestSchema: "EvolutionSnapshotRequest",
    responseSchema: "EvolutionSnapshotResponse",
    authRequired: true,
  },
  {
    method: "DELETE",
    path: "/api/v1/evolucao/snapshots/{snapshotId}",
    resource: RESOURCE_NAMES.evolucao,
    requestSchema: "Empty",
    responseSchema: "OperationResponse",
    authRequired: true,
  },
];

module.exports = {
  API_V1_ROUTES,
};
